---
# Ansible Collections
collections:
  - name: community.general
    version: ">=7.0.0"
  - name: community.mysql
    version: ">=3.0.0"
  - name: community.docker
    version: ">=3.0.0"
  - name: ansible.posix
    version: ">=1.5.0"

# Ansible Roles (if needed)
roles: []
